# Generated by Django 5.2.14 on 2026-05-06 19:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('slug', models.SlugField(unique=True)),
            ],
            options={
                'verbose_name': 'category',
                'verbose_name_plural': 'categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='title')),
                ('description', models.TextField(verbose_name='description')),
                ('location', models.CharField(max_length=100, verbose_name='location')),
                ('price_per_day', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='price per day')),
                ('price_per_weekend', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='price per weekend')),
                ('price_per_week', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='price per week')),
                ('price_per_month', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='price per month')),
                ('base_fee', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='base fee')),
                ('payment_methods', models.CharField(blank=True, max_length=200, verbose_name='preferred payment methods')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='quantity')),
                ('auto_accept', models.BooleanField(default=False, verbose_name='auto-accept bookings')),
                ('auto_accept_message', models.TextField(blank=True, verbose_name='auto-accept message')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='listings', to='listings.category', verbose_name='category')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listings', to=settings.AUTH_USER_MODEL, verbose_name='owner')),
            ],
            options={
                'verbose_name': 'listing',
                'verbose_name_plural': 'listings',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BlockedDateRange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(verbose_name='start date')),
                ('end_date', models.DateField(verbose_name='end date')),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocked_dates', to='listings.listing', verbose_name='listing')),
            ],
            options={
                'ordering': ['start_date'],
            },
        ),
        migrations.CreateModel(
            name='ListingPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='listings/', verbose_name='image')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='order')),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='listings.listing', verbose_name='listing')),
            ],
            options={
                'ordering': ['order', 'pk'],
            },
        ),
    ]
