# Generated by Django 5.2.14 on 2026-05-13 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='delivery_fee',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='delivery fee'),
        ),
        migrations.AddField(
            model_name='listing',
            name='deposit',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='refundable deposit'),
        ),
        migrations.AddField(
            model_name='listing',
            name='minimum_days',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='minimum rental period (days)'),
        ),
    ]
