# Generated by Django 5.2.14 on 2026-05-13 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_add_deposit_delivery_fee_minimum_days'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='view_count',
            field=models.PositiveIntegerField(default=0, verbose_name='view count'),
        ),
    ]
