# Generated by Django 5.2.14 on 2026-05-13 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_sitesettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='max_active_listings',
            field=models.PositiveIntegerField(default=20, help_text='Maximum number of active listings a user can have. Per-user overrides take precedence.', verbose_name='max active listings per user'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='max_pending_bookings',
            field=models.PositiveIntegerField(default=10, help_text='Maximum number of pending booking requests a user can have at once. Per-user overrides take precedence.', verbose_name='max pending bookings per user'),
        ),
        migrations.AddField(
            model_name='user',
            name='max_active_listings_override',
            field=models.PositiveIntegerField(blank=True, help_text='Leave blank to use the site-wide default.', null=True, verbose_name='max active listings override'),
        ),
        migrations.AddField(
            model_name='user',
            name='max_pending_bookings_override',
            field=models.PositiveIntegerField(blank=True, help_text='Leave blank to use the site-wide default.', null=True, verbose_name='max pending bookings override'),
        ),
    ]
